[TM1-40]Implement Feedback for Mentors
patternica/internship-be-team1 pull request #31
Opened 2021-01-19 23:11 UTC by PrivalovaOlha

2021-01-23 21:04 UTC, patternica requested changes

2021-01-23 21:04 UTC, patternica commented on src/main/java/com/patternica/internship/service/impl/UserServiceImpl.java
> +        double updatedAverage = (user.getRating() * (countOfEstimates - 1) + newRating) / countOfEstimates;
Can be there be 4.31234234234234? I think round should be there. https://stackoverflow.com/questions/2808535/round-a-double-to-2-decimal-places

2021-01-23 21:20 UTC, PrivalovaOlha commented on src/main/java/com/patternica/internship/service/impl/UserServiceImpl.java
> +        long countOfEstimates = profile.getReviews().stream().map(Review::getRating).filter(r -> r > 0).count();
Can we have a review without a rating? If not, I will do profile.getReviews().size(). Or I should decide it by myself?

2021-01-24 18:13 UTC, deemch3k requested changes

2021-01-24 18:13 UTC, deemch3k commented on src/main/java/com/patternica/internship/controller/ReviewController.java
> +    }
I am not sure that this good practice to get a list of reviews by ids. first of all, in your swagger documentation, you write "Get by id" but you require a list of ids, secondary you can get the list of reviews by profile id in ProfileController by creating endpoint with /profiles/id/reviews URL.

2021-01-24 18:46 UTC, PrivalovaOlha commented on src/main/java/com/patternica/internship/controller/ReviewController.java
> +    }
Agree that swagger documentation was written incorrectly.

If I make  /profiles/id/reviews URL. It will send all reviews?
The frontend has no need to get all reviews by one request. It is better to show only part of all reviews and get next part if the user wants to see more

2021-01-24 19:08 UTC, deemch3k commented on src/main/java/com/patternica/internship/controller/ReviewController.java
> +    }
@PrivalovaOlha You will send reviews of the particular user profile.
If you need to send only part of reviews you can take in the URL parameter size which will define how many reviews you need to return on the client, probably if those reviews are required to shows by different pages you can implement pagination

2021-01-27 19:25 UTC, deemch3k approved these changes

2021-01-29 11:40 UTC, patternica approved these changes

2021-01-29 14:42 UTC, merged